spring.application.name=CardGeneratorHenriqueSouzaDaSilva
server.port=0
spring.main.web-application-type=servlet

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:card
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=card
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console (acesso via /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
